Repository getsentry/gib-potato, pull requests merged in 2025-04, with the labels that each got.

#275 feat(fronted|backend): New feature
  .env.example
  composer.json
  composer.lock
  config/Migrations/20250327011328_AddStocks.php
  config/Migrations/20250331224702_AddCredits.php
  config/Migrations/20250401005737_AddConfig.php
  config/Seeds/StockMarketSeedSeed.php
  config/app.php
  config/routes.php
  docker-compose.yml
  docker/backend/run.sh
  frontend/src/components/Filter.vue
  frontend/src/components/Leaderboard.vue
  frontend/src/components/MainMenu.vue
  frontend/src/components/StocksLeaderboard.vue
  frontend/src/main.js
  frontend/src/router/index.js
  frontend/src/store/index.js
  frontend/src/views/Home.vue
  frontend/src/views/Shop.vue
  frontend/src/views/Stocks.vue
  package-lock.json
  package.json
  src/Application.php
  src/Command/AnnounceStockMarketCommand.php
  src/Command/ExecuteTradesCommand.php
  src/Command/GenerateInitialSharePricesCommand.php
  src/Command/GenerateInitialSharesCommand.php
  src/Command/GenerateInitialTradesCommand.php
  src/Command/OpenStockMarketCommand.php
  src/Controller/Api/LeaderBoardController.php
  src/Controller/Api/StocksController.php
  src/Controller/CreditsController.php
  src/Model/Entity/Credit.php
  src/Model/Entity/Share.php
  src/Model/Entity/SharePrice.php
  src/Model/Entity/Stock.php
  src/Model/Entity/Trade.php
  src/Model/Entity/User.php
  src/Model/Table/CreditsTable.php
  src/Model/Table/SharePricesTable.php
  src/Model/Table/SharesTable.php
  src/Model/Table/StocksTable.php
  src/Model/Table/TradesTable.php
  templates/Credits/index.php
  tests/Fixture/CreditsFixture.php
  tests/Fixture/SharePricesFixture.php
  tests/Fixture/SharesFixture.php
  tests/Fixture/StocksFixture.php
  tests/Fixture/TradesFixture.php
Labels: feature

#276 fix(backend): Improve `/api/leaderboard` performance
  src/Controller/Api/LeaderBoardController.php
  src/Model/Table/UsersTable.php
Labels: bug

#277 feat(frontend|backend): Add `/trades`
  config/routes.php
  frontend/src/components/MainMenu.vue
  frontend/src/main.js
  frontend/src/router/index.js
  frontend/src/store/index.js
  frontend/src/views/Trades.vue
  src/Controller/Api/StocksController.php
Labels: feature

#279 ref(frontend|backend): Improve `/trades`
  frontend/src/views/Trades.vue
  src/Controller/Api/StocksController.php
Labels: improvement

#282 fix(backend): Pass required argument
  src/Command/ExecuteTradesCommand.php
Labels: bug

#284 fix(backend): Do not mark orders as canceled due to a lack of fund.
  src/Command/ExecuteTradesCommand.php
Labels: bug

#278 Completely untested vibcoded order cancellation
  config/routes.php
  frontend/src/views/Stocks.vue
  src/Controller/Api/StocksController.php
Labels: feature

#288 fix(docker): Get me stacktrace args
  docker/backend/Dockerfile
Labels: improvement

#289 fix(backend): Fix rounding
  src/Command/ExecuteTradesCommand.php
Labels: bug

#290 fix(frontend): Maybe fix sell modal on un-owned stock
  frontend/src/views/Stocks.vue
Labels: bug

#297 fix(backend): Enable PHP stacktrace args
  docker/backend/Dockerfile
Labels: bug

#298 chore(frontend|backend|potel): Bump deps
  composer.json
  composer.lock
  package-lock.json
  package.json
  potal/go.mod
  potal/go.sum
  potal/handler.go
  potal/main.go
Labels: dependencies

#293 feat(frontend): Use `Sentry.consoleLoggingIntegration`
  frontend/src/main.js
  frontend/src/store/index.js
Labels: improvement

#299 chore(backend): Bump Sentry SDK
  composer.json
  composer.lock
Labels: dependencies

#300 feat(backend): Try out Sentry logs
  composer.json
  composer.lock
  src/Middleware/SentryMiddleware.php
  src/Service/AwardService.php
Labels: feature
